[package]
name = "dla"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
#build = "scripts/build.rs"


[dependencies]
time = "0.1"
rand = "0.3"
itertools = "0.5"
newtype-ops = "0.1.3"
#rustimization = "*"

[dependencies.ncg_min]
git = "https://github.com/rekka/ncg_min"

[dependencies.homogenous]
git = "file:///home/lampam/cpp/other/rust/homogenous"

[dependencies.dla-sys]
git = "file:///home/lampam/asd/class/research/dla-sys"
